using UnityEngine;

[System.Serializable]
public partial class Wearable
{
    public enum SlotEnum { NA, Body, Face, Eyes, Head, Hand, Pet }
    public enum RarityEnum { NA, Common, Uncommon, Rare, Legendary, Mythical, Godlike }
    public enum WeaponTypeEnum { NA, Unarmed, Cleave, Smash, Pierce, Ballistic, Magic, Splash, Consume, Aura, Throw, Shield }
    public enum BuffEnum { 
        None,
        NA,

        // primary (from NetworkCharacter)
        HpMax,
        HpBuffer,
        AttackPower,
        CriticalChance,
        ApMax,
        ApBuffer,
        DoubleStrikeChance,
        CriticalDamage,
        MoveSpeed,
        Accuracy,
        Evasion,

        // attack
        CriticalDamageIncrease,
        DebuffEffectiveness,
        SpecialCooldownReduction,
        Piercing,
        SpecialCostReduction,
        AttackRange,

        // defense
        ReduceMeleeDamage,
        ReduceRangedDamage,
        ReduceElementalDamage,
        Block,
        ApLeech,
        HpLeech,
        EssenceLeech,

        // environment
        Magnetism,
        ExtraDash,
        Purveying,

        // debuffs
        Poison,
        Weak,
        RootChance,
        BleedChance,
        BurnChance,
        SlowChance,
        ShockChance,
        BlindChance,
    }

    public SlotEnum Slot;
    public int Id;
    public string Name;
    public NameEnum NameType;
    public RarityEnum Rarity;
    public int Nrg;
    public int Agg;
    public int Spk;
    public int Brn;
    public WeaponTypeEnum WeaponType;
    public int SpecialAp;
    public int SpecialCooldown;
    public BuffEnum SecondaryBuff;
    public float SecondaryBuffValue;
    public BuffEnum TertiaryBuff;
    public float TertiaryBuffValue;
    public string SwapDescription;
}


public partial class Wearable {
    public enum NameEnum {
        _10GallonHat,
        _1337Laptop,
        _23Jersey,
        _32ETHCoin,
        _3DGlasses,
        AagentFedoraHat,
        AagentHeadset,
        AagentPistol,
        AagentShades,
        AagentShirt,
        AantennaBot,
        AastronautHelmet,
        AastronautSuit,
        AaveBoat,
        AaveFlag,
        AaveHeroMask,
        AaveHeroShirt,
        AavePlushToy,
        AlchemicaApron,
        AllSeeingEyes,
        AlluringEyes,
        AnimalSkins,
        ApeMask,
        AppleJuice,
        APYShades,
        Aviators,
        BabyBottle,
        Bandage,
        Basketball,
        BeardofDivinity,
        BeardofWisdom,
        BedtimeMilk,
        BeerHelmet,
        BigGHSTToken,
        BikerHelmet,
        BikerJacket,
        BitcoinBeanie,
        BitcoinGuitar,
        BlackJeans,
        BlockScanners,
        BlueCacti,
        BlueHawaiianShirt,
        BluePlaid,
        BowandArrow,
        BrunettePonytail,
        BushyEyebrows,
        CamoHat,
        CamoPants,
        CandyJaar,
        CaptainAaveMask,
        CaptainAaveShield,
        CaptainAaveSuit,
        CitaadelHelm,
        Clutch,
        Coconut,
        CoderdanShades,
        CoinGeckoTee,
        ComfyPoncho,
        CommonRofl,
        CommonWizardHat,
        CommonWizardStaff,
        CoolShades,
        CyborgEye,
        DAOEgg,
        DayDress,
        DoublesidedAxe,
        DragonHorns,
        DragonWings,
        EagleMask,
        ElfEars,
        EnergyGun,
        ETHLogoGlasses,
        ETHTShirt,
        EyesofDevotion,
        Faangs,
        FairyWings,
        FAKEBeret,
        FAKEShirt,
        FarmerJeans,
        FeatheredCap,
        Fireball,
        FlamingApron,
        FlowerStuds,
        FluffyPillow,
        ForgeGoggles,
        ForkedBeard,
        FoxyMask,
        FoxyTail,
        GalaxyBrain,
        GameController,
        GamerJacket,
        GeckoEyes,
        GeckoHat,
        GeishaHeadpiece,
        GemstoneRing,
        GentlemanCoat,
        GentlemanHat,
        Geo,
        GeodeSmasher,
        GldnXrossRobe,
        GMSeeds,
        GOATee,
        GodlikeCacti,
        GodlikeWizardHat,
        GodliLocks,
        GoldNecklace,
        GotchiMug,
        GuyFawkesMask,
        H4xx0rShirt,
        HaanzoKatana,
        HalfRektShirt,
        Handsaw,
        HazmatHood,
        HazmatSuit,
        Headphones,
        HeavenlyRobes,
        HookHand,
        HornedHelmet,
        HorseshoeMustache,
        ImperialMoustache,
        JaayGlasses,
        JaayHairpiece,
        JaaySuit,
        JamaicanFlag,
        JordanHair,
        JordanSuit,
        KabutoHelmet,
        Kimono,
        L2Sign,
        Lasso,
        LeatherTunic,
        LegendaryRofl,
        LegendaryWizardHat,
        LegendaryWizardStaff,
        LensnFrensPlant,
        LickBrain,
        LickEyes,
        LickTentacle,
        LickTongue,
        LilBubbleSpaceSuit,
        LilPumpDrank,
        LilPumpDreads,
        LilPumpGoatee,
        LilPumpShades,
        LilPumpThreads,
        LinkBubbly,
        LINKCube,
        LinkMessDress,
        LinkWhiteHat,
        LlamacornShirt,
        Longbow,
        M67Grenade,
        MarcHair,
        MarcOutfit,
        MarineCap,
        MarineJacket,
        Martini,
        MatrixEyes,
        MechanicalClaw,
        Milkshake,
        MinerHelmet,
        MinerJeans,
        MK2Grenade,
        Mohawk,
        Monocle,
        MudgenDiamond,
        MuttonChops,
        MythicalCacti,
        MythicalRofl,
        MythicalWizardHat,
        NailGun,
        Nimbus,
        NogaraArmor,
        Null,
        OKexSign,
        OliversSpoon,
        Overalls,
        PaintBrush,
        PaintPalette,
        PajamaHat,
        PajamaShirt,
        PaperFan,
        Parasol,
        PartyDress,
        Pickaxe,
        PillboxHat,
        PirateCoat,
        PirateHat,
        PiratePatch,
        Pitchfork,
        PixelcraftSquare,
        PixelcraftTee,
        PlasticEarrings,
        PlateArmor,
        PlateShield,
        PointyHorns,
        PolygonCap,
        PolygonShirt,
        PonchoHoodie,
        PortalMageArmor,
        PortalMageAxe,
        PortalMageBlackAxe,
        PortalMageHelmet,
        PrincessHair,
        PrincessTiara,
        PunkShirt,
        RadarEyes,
        RainbowVomit,
        RareRofl,
        RastaHat,
        RastaShirt,
        RedHair,
        RedHawaiianShirt,
        RedHeadband,
        RedPlaid,
        RedSantaHat,
        REKTSign,
        Roflnoggin,
        RoyalCrown,
        RoyalRobes,
        RoyalRofl,
        RoyalScepter,
        SafetyGlasses,
        SandboxHoodie,
        SebastienHair,
        SergeyBeard,
        SergeyEyes,
        ShaamanHoodie,
        ShaamanPoncho,
        SignalHeadset,
        Skateboard,
        SlicksSurfboard,
        SnapshotCap,
        SnapshotShirt,
        SnowCamoHat,
        SnowCamoPants,
        SpaceHelmet,
        SpiritSword,
        StaffofCharming,
        StaffofCreation,
        StaniHair,
        StaniLifejacket,
        SteampunkGoggles,
        SteampunkTrousers,
        StrawHat,
        SusButterfly,
        SushiBandana,
        SushiCoat,
        SushiKnife,
        SushiPiece,
        Sweatband,
        TaoistRobe,
        ThaaveHammer,
        ThaaveHelmet,
        ThaaveSuit,
        TintedShades,
        TinyCrown,
        TrackShorts,
        TrackSuit,
        TrezorWallet,
        uGOTCHIToken,
        UncommonCacti,
        UncommonRofl,
        UpArrow,
        UpOnlyShirt,
        UraniumRod,
        VNeckShirt,
        VoteSign,
        VoxelEyes,
        VRHeadset,
        WagieCap,
        WaifuPillow,
        WalkieTalkie,
        Waterbottle,
        WaterJug,
        WavyHair,
        WGMIShirt,
        Wine,
        WitchyCloak,
        WitchyHat,
        WitchyWand,
        WizardVisor,
        WraanglerJeans,
        XibotMohawk,
        YellowManbun,
        YoroiArmor,

        Unarmed,
        None,
    }

}