//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""2d625acc-f075-4881-a46e-0a9d8435740a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""ebb0a0c2-5486-4241-a842-1e741b6711a5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""ad44f849-6f7e-4544-85ce-47d92a95273d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""__________"",
                    ""type"": ""Button"",
                    ""id"": ""d6759d90-9e17-469b-8214-508f2dbcdb04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""835c6ec1-a8ce-418c-a0bf-23a62364f764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftAttack_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""ede36fc0-ffc6-4227-ab97-549443fe4d4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSpecial_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""b68945a9-54ff-4f89-98ad-2928283c45ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHoldStart_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""591e7e0e-e736-4805-862b-2199caf74661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHoldFinish_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""9cff82ec-67d3-43be-af1a-fa251bc0cae2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightAttack_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""05a5f118-4cb5-4707-95bc-0fcf9b80f7b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSpecial_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""b458bd03-e856-4f5b-89e6-8da48167df1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHoldStart_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""d7fedef8-db6b-46db-875a-07d5aae0933f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHoldFinish_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""6944e948-ee74-42f7-8db1-34f312913d0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""________"",
                    ""type"": ""Button"",
                    ""id"": ""d7b4cce0-1305-4da8-9feb-ca42e7d341cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""be7e15c2-d544-4cc8-9874-03d6dbca7466"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftAttack_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""67df635f-5719-4509-8ef4-7917dc2ac103"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSpecial_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""8bf5cc78-2692-430f-a5fd-6aaa352595e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHoldStart_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""7631db63-9c42-4b09-bf1f-c44b32f4cfc6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHoldFinish_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""d9dbef72-519d-4f10-86d6-8600e68da700"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightAttack_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""b08efc8c-9a09-4fd7-85d7-39c3959034c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSpecial_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""ba347113-55eb-43fd-a20b-f97339d39913"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHoldStart_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""889086ac-60d5-4a87-a3e5-9b16afede31c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHoldFinish_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""43532aa2-f0d1-4284-ae62-d15982bcf753"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""_______"",
                    ""type"": ""Button"",
                    ""id"": ""9cfbd604-c520-434a-82ea-2f851fd6882e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Value"",
                    ""id"": ""5e45fcb7-31bf-4580-80c0-421b4b260c9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FreezeMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c49d5306-0c72-4a73-b3f7-781b46cbd47d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""a374a599-2756-4be9-aa60-639f72424b82"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""52ba9251-555d-4d1b-bd82-2ef218d9b70e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9c5f7af7-edad-4e07-bb4b-e1a515e5d701"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""35c1c48e-28e8-43b4-869f-2c010cbb7c7b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cb07142a-dc44-41b1-83de-672dba18126b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d15e3977-e4da-4e5f-b5ac-fc951ff65290"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0029874d-a637-4653-92c2-d0c6cbc5e3b2"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5544f6aa-c0e0-4d95-92d5-8c62c3c5d8a0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e71ad0a-8f3a-4d9d-a9ac-67c8b256871e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAttack_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be8b19a2-d0ea-4c65-9476-bb6df62201c3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightAttack_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""351f8a5d-5090-4787-842a-7bd5d547b536"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldStart_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feea3e16-5d3a-437d-96f6-531edc11ce47"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldFinish_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1b8dd98-143b-4f62-9edb-11931700755e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldStart_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d5426ea-fc17-4caf-90fe-241357cf6006"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldFinish_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd50dffe-d4e3-4994-be40-50c3bdf5037c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSpecial_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1996d5ae-8aa1-49ae-b3a4-e8b0df9d925c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSpecial_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24e3bf9f-732b-4825-ba2c-495abf85bc68"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""__________"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28920e30-dbe3-474c-8de4-c257a23f0c69"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""________"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""817c87e4-ef52-4e79-b0e5-8153c44338f3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""_______"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df598ed1-f0c6-4758-9c3e-543ea5b045a9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b9b8066-17f6-4846-9c17-72e6f7c7d2de"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e7ce4ca-9b76-4eaf-8cb8-4237e56a862e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAttack_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cee60d51-9e0f-4b56-b6a0-7fadf97089fd"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAttack_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8f29bb2-ce9f-4b5c-bb87-187cae6a1a57"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8226e69d-bba4-4d19-bae9-f693bb05509d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightAttack_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""638033e9-b59b-4669-b7e6-5556f2b8b1ef"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightAttack_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ed018c-2073-43e9-943e-de34f9443961"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51e47168-0574-4998-aba7-579fd6ec5f33"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dad3403f-31d7-4392-aa36-47df74e4e1c7"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSpecial_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ec4016f-57ac-4329-9174-1b4d79eff491"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSpecial_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""430c3027-a46f-45c2-9bf1-125c9a90ff14"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSpecial_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f684272c-8a57-48cd-8669-a0f080af5c5f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSpecial_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52a5680c-e8df-4b42-b95a-55a32f7b78f1"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldStart_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4d968be-0710-4592-b6c0-25657f2d54fd"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldStart_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e1ed4d7-4253-4ced-8b8a-688954a47aa0"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldFinish_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41a422b9-060c-4b98-a4a6-527b1327978e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldFinish_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f3b43ac-f080-4d05-85a0-a206db705349"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldStart_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b22bf005-40b5-4c37-8c1d-ec601c811b27"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldStart_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e21dc8b-5358-4673-9f2f-c94115d38f82"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldFinish_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""776d0c55-c723-448e-9d5e-368a23e3bc68"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldFinish_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""437d2b3a-1d8e-4956-b4e9-f54af87c5a2a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreezeMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75c672cc-3619-4506-8f46-a1498cdeda91"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreezeMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07929ebc-9a38-4b7a-bf60-c0b50be3e019"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreezeMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InUI"",
            ""id"": ""aeadba0a-900f-4cab-a49d-0c284a3768fb"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""e8b1b68e-4180-4d7c-801c-c70388f84abb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""fa6c5625-6b4f-48a2-8067-91879ff6d591"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""0f87f14f-9ec1-45d4-9af6-4c0707efc05b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""388cbaa2-a9e7-49af-ae01-c1529dc2eca4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""51a82934-9bbc-4aa6-93a0-7a551f2567dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9e2f7212-8283-43f0-989f-7923dafd0203"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ec20bc6-69ec-42ca-8e77-72210eb6092e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""522e9353-f583-4fe0-9f57-e1eb60f20f3c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09d63f20-e7ee-41e6-bfd4-7a07e2ccbd07"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9f8691d-d2f4-44da-8ba4-1689f1ac618b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Movement = m_InGame.FindAction("Movement", throwIfNotFound: true);
        m_InGame_MousePosition = m_InGame.FindAction("MousePosition", throwIfNotFound: true);
        m_InGame___________ = m_InGame.FindAction("__________", throwIfNotFound: true);
        m_InGame_Dash_CursorAim = m_InGame.FindAction("Dash_CursorAim", throwIfNotFound: true);
        m_InGame_LeftAttack_CursorAim = m_InGame.FindAction("LeftAttack_CursorAim", throwIfNotFound: true);
        m_InGame_LeftSpecial_CursorAim = m_InGame.FindAction("LeftSpecial_CursorAim", throwIfNotFound: true);
        m_InGame_LeftHoldStart_CursorAim = m_InGame.FindAction("LeftHoldStart_CursorAim", throwIfNotFound: true);
        m_InGame_LeftHoldFinish_CursorAim = m_InGame.FindAction("LeftHoldFinish_CursorAim", throwIfNotFound: true);
        m_InGame_RightAttack_CursorAim = m_InGame.FindAction("RightAttack_CursorAim", throwIfNotFound: true);
        m_InGame_RightSpecial_CursorAim = m_InGame.FindAction("RightSpecial_CursorAim", throwIfNotFound: true);
        m_InGame_RightHoldStart_CursorAim = m_InGame.FindAction("RightHoldStart_CursorAim", throwIfNotFound: true);
        m_InGame_RightHoldFinish_CursorAim = m_InGame.FindAction("RightHoldFinish_CursorAim", throwIfNotFound: true);
        m_InGame_________ = m_InGame.FindAction("________", throwIfNotFound: true);
        m_InGame_Dash_MoveAim = m_InGame.FindAction("Dash_MoveAim", throwIfNotFound: true);
        m_InGame_LeftAttack_MoveAim = m_InGame.FindAction("LeftAttack_MoveAim", throwIfNotFound: true);
        m_InGame_LeftSpecial_MoveAim = m_InGame.FindAction("LeftSpecial_MoveAim", throwIfNotFound: true);
        m_InGame_LeftHoldStart_MoveAim = m_InGame.FindAction("LeftHoldStart_MoveAim", throwIfNotFound: true);
        m_InGame_LeftHoldFinish_MoveAim = m_InGame.FindAction("LeftHoldFinish_MoveAim", throwIfNotFound: true);
        m_InGame_RightAttack_MoveAim = m_InGame.FindAction("RightAttack_MoveAim", throwIfNotFound: true);
        m_InGame_RightSpecial_MoveAim = m_InGame.FindAction("RightSpecial_MoveAim", throwIfNotFound: true);
        m_InGame_RightHoldStart_MoveAim = m_InGame.FindAction("RightHoldStart_MoveAim", throwIfNotFound: true);
        m_InGame_RightHoldFinish_MoveAim = m_InGame.FindAction("RightHoldFinish_MoveAim", throwIfNotFound: true);
        m_InGame________ = m_InGame.FindAction("_______", throwIfNotFound: true);
        m_InGame_Interact = m_InGame.FindAction("Interact", throwIfNotFound: true);
        m_InGame_FreezeMovement = m_InGame.FindAction("FreezeMovement", throwIfNotFound: true);
        // InUI
        m_InUI = asset.FindActionMap("InUI", throwIfNotFound: true);
        m_InUI_Up = m_InUI.FindAction("Up", throwIfNotFound: true);
        m_InUI_Down = m_InUI.FindAction("Down", throwIfNotFound: true);
        m_InUI_Left = m_InUI.FindAction("Left", throwIfNotFound: true);
        m_InUI_Right = m_InUI.FindAction("Right", throwIfNotFound: true);
        m_InUI_Select = m_InUI.FindAction("Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Movement;
    private readonly InputAction m_InGame_MousePosition;
    private readonly InputAction m_InGame___________;
    private readonly InputAction m_InGame_Dash_CursorAim;
    private readonly InputAction m_InGame_LeftAttack_CursorAim;
    private readonly InputAction m_InGame_LeftSpecial_CursorAim;
    private readonly InputAction m_InGame_LeftHoldStart_CursorAim;
    private readonly InputAction m_InGame_LeftHoldFinish_CursorAim;
    private readonly InputAction m_InGame_RightAttack_CursorAim;
    private readonly InputAction m_InGame_RightSpecial_CursorAim;
    private readonly InputAction m_InGame_RightHoldStart_CursorAim;
    private readonly InputAction m_InGame_RightHoldFinish_CursorAim;
    private readonly InputAction m_InGame_________;
    private readonly InputAction m_InGame_Dash_MoveAim;
    private readonly InputAction m_InGame_LeftAttack_MoveAim;
    private readonly InputAction m_InGame_LeftSpecial_MoveAim;
    private readonly InputAction m_InGame_LeftHoldStart_MoveAim;
    private readonly InputAction m_InGame_LeftHoldFinish_MoveAim;
    private readonly InputAction m_InGame_RightAttack_MoveAim;
    private readonly InputAction m_InGame_RightSpecial_MoveAim;
    private readonly InputAction m_InGame_RightHoldStart_MoveAim;
    private readonly InputAction m_InGame_RightHoldFinish_MoveAim;
    private readonly InputAction m_InGame________;
    private readonly InputAction m_InGame_Interact;
    private readonly InputAction m_InGame_FreezeMovement;
    public struct InGameActions
    {
        private @PlayerInputs m_Wrapper;
        public InGameActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_InGame_Movement;
        public InputAction @MousePosition => m_Wrapper.m_InGame_MousePosition;
        public InputAction @__________ => m_Wrapper.m_InGame___________;
        public InputAction @Dash_CursorAim => m_Wrapper.m_InGame_Dash_CursorAim;
        public InputAction @LeftAttack_CursorAim => m_Wrapper.m_InGame_LeftAttack_CursorAim;
        public InputAction @LeftSpecial_CursorAim => m_Wrapper.m_InGame_LeftSpecial_CursorAim;
        public InputAction @LeftHoldStart_CursorAim => m_Wrapper.m_InGame_LeftHoldStart_CursorAim;
        public InputAction @LeftHoldFinish_CursorAim => m_Wrapper.m_InGame_LeftHoldFinish_CursorAim;
        public InputAction @RightAttack_CursorAim => m_Wrapper.m_InGame_RightAttack_CursorAim;
        public InputAction @RightSpecial_CursorAim => m_Wrapper.m_InGame_RightSpecial_CursorAim;
        public InputAction @RightHoldStart_CursorAim => m_Wrapper.m_InGame_RightHoldStart_CursorAim;
        public InputAction @RightHoldFinish_CursorAim => m_Wrapper.m_InGame_RightHoldFinish_CursorAim;
        public InputAction @________ => m_Wrapper.m_InGame_________;
        public InputAction @Dash_MoveAim => m_Wrapper.m_InGame_Dash_MoveAim;
        public InputAction @LeftAttack_MoveAim => m_Wrapper.m_InGame_LeftAttack_MoveAim;
        public InputAction @LeftSpecial_MoveAim => m_Wrapper.m_InGame_LeftSpecial_MoveAim;
        public InputAction @LeftHoldStart_MoveAim => m_Wrapper.m_InGame_LeftHoldStart_MoveAim;
        public InputAction @LeftHoldFinish_MoveAim => m_Wrapper.m_InGame_LeftHoldFinish_MoveAim;
        public InputAction @RightAttack_MoveAim => m_Wrapper.m_InGame_RightAttack_MoveAim;
        public InputAction @RightSpecial_MoveAim => m_Wrapper.m_InGame_RightSpecial_MoveAim;
        public InputAction @RightHoldStart_MoveAim => m_Wrapper.m_InGame_RightHoldStart_MoveAim;
        public InputAction @RightHoldFinish_MoveAim => m_Wrapper.m_InGame_RightHoldFinish_MoveAim;
        public InputAction @_______ => m_Wrapper.m_InGame________;
        public InputAction @Interact => m_Wrapper.m_InGame_Interact;
        public InputAction @FreezeMovement => m_Wrapper.m_InGame_FreezeMovement;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @__________.started += instance.On__________;
            @__________.performed += instance.On__________;
            @__________.canceled += instance.On__________;
            @Dash_CursorAim.started += instance.OnDash_CursorAim;
            @Dash_CursorAim.performed += instance.OnDash_CursorAim;
            @Dash_CursorAim.canceled += instance.OnDash_CursorAim;
            @LeftAttack_CursorAim.started += instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.performed += instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.canceled += instance.OnLeftAttack_CursorAim;
            @LeftSpecial_CursorAim.started += instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.performed += instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.canceled += instance.OnLeftSpecial_CursorAim;
            @LeftHoldStart_CursorAim.started += instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.performed += instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.canceled += instance.OnLeftHoldStart_CursorAim;
            @LeftHoldFinish_CursorAim.started += instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.performed += instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.canceled += instance.OnLeftHoldFinish_CursorAim;
            @RightAttack_CursorAim.started += instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.performed += instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.canceled += instance.OnRightAttack_CursorAim;
            @RightSpecial_CursorAim.started += instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.performed += instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.canceled += instance.OnRightSpecial_CursorAim;
            @RightHoldStart_CursorAim.started += instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.performed += instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.canceled += instance.OnRightHoldStart_CursorAim;
            @RightHoldFinish_CursorAim.started += instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.performed += instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.canceled += instance.OnRightHoldFinish_CursorAim;
            @________.started += instance.On________;
            @________.performed += instance.On________;
            @________.canceled += instance.On________;
            @Dash_MoveAim.started += instance.OnDash_MoveAim;
            @Dash_MoveAim.performed += instance.OnDash_MoveAim;
            @Dash_MoveAim.canceled += instance.OnDash_MoveAim;
            @LeftAttack_MoveAim.started += instance.OnLeftAttack_MoveAim;
            @LeftAttack_MoveAim.performed += instance.OnLeftAttack_MoveAim;
            @LeftAttack_MoveAim.canceled += instance.OnLeftAttack_MoveAim;
            @LeftSpecial_MoveAim.started += instance.OnLeftSpecial_MoveAim;
            @LeftSpecial_MoveAim.performed += instance.OnLeftSpecial_MoveAim;
            @LeftSpecial_MoveAim.canceled += instance.OnLeftSpecial_MoveAim;
            @LeftHoldStart_MoveAim.started += instance.OnLeftHoldStart_MoveAim;
            @LeftHoldStart_MoveAim.performed += instance.OnLeftHoldStart_MoveAim;
            @LeftHoldStart_MoveAim.canceled += instance.OnLeftHoldStart_MoveAim;
            @LeftHoldFinish_MoveAim.started += instance.OnLeftHoldFinish_MoveAim;
            @LeftHoldFinish_MoveAim.performed += instance.OnLeftHoldFinish_MoveAim;
            @LeftHoldFinish_MoveAim.canceled += instance.OnLeftHoldFinish_MoveAim;
            @RightAttack_MoveAim.started += instance.OnRightAttack_MoveAim;
            @RightAttack_MoveAim.performed += instance.OnRightAttack_MoveAim;
            @RightAttack_MoveAim.canceled += instance.OnRightAttack_MoveAim;
            @RightSpecial_MoveAim.started += instance.OnRightSpecial_MoveAim;
            @RightSpecial_MoveAim.performed += instance.OnRightSpecial_MoveAim;
            @RightSpecial_MoveAim.canceled += instance.OnRightSpecial_MoveAim;
            @RightHoldStart_MoveAim.started += instance.OnRightHoldStart_MoveAim;
            @RightHoldStart_MoveAim.performed += instance.OnRightHoldStart_MoveAim;
            @RightHoldStart_MoveAim.canceled += instance.OnRightHoldStart_MoveAim;
            @RightHoldFinish_MoveAim.started += instance.OnRightHoldFinish_MoveAim;
            @RightHoldFinish_MoveAim.performed += instance.OnRightHoldFinish_MoveAim;
            @RightHoldFinish_MoveAim.canceled += instance.OnRightHoldFinish_MoveAim;
            @_______.started += instance.On_______;
            @_______.performed += instance.On_______;
            @_______.canceled += instance.On_______;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @FreezeMovement.started += instance.OnFreezeMovement;
            @FreezeMovement.performed += instance.OnFreezeMovement;
            @FreezeMovement.canceled += instance.OnFreezeMovement;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @__________.started -= instance.On__________;
            @__________.performed -= instance.On__________;
            @__________.canceled -= instance.On__________;
            @Dash_CursorAim.started -= instance.OnDash_CursorAim;
            @Dash_CursorAim.performed -= instance.OnDash_CursorAim;
            @Dash_CursorAim.canceled -= instance.OnDash_CursorAim;
            @LeftAttack_CursorAim.started -= instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.performed -= instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.canceled -= instance.OnLeftAttack_CursorAim;
            @LeftSpecial_CursorAim.started -= instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.performed -= instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.canceled -= instance.OnLeftSpecial_CursorAim;
            @LeftHoldStart_CursorAim.started -= instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.performed -= instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.canceled -= instance.OnLeftHoldStart_CursorAim;
            @LeftHoldFinish_CursorAim.started -= instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.performed -= instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.canceled -= instance.OnLeftHoldFinish_CursorAim;
            @RightAttack_CursorAim.started -= instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.performed -= instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.canceled -= instance.OnRightAttack_CursorAim;
            @RightSpecial_CursorAim.started -= instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.performed -= instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.canceled -= instance.OnRightSpecial_CursorAim;
            @RightHoldStart_CursorAim.started -= instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.performed -= instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.canceled -= instance.OnRightHoldStart_CursorAim;
            @RightHoldFinish_CursorAim.started -= instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.performed -= instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.canceled -= instance.OnRightHoldFinish_CursorAim;
            @________.started -= instance.On________;
            @________.performed -= instance.On________;
            @________.canceled -= instance.On________;
            @Dash_MoveAim.started -= instance.OnDash_MoveAim;
            @Dash_MoveAim.performed -= instance.OnDash_MoveAim;
            @Dash_MoveAim.canceled -= instance.OnDash_MoveAim;
            @LeftAttack_MoveAim.started -= instance.OnLeftAttack_MoveAim;
            @LeftAttack_MoveAim.performed -= instance.OnLeftAttack_MoveAim;
            @LeftAttack_MoveAim.canceled -= instance.OnLeftAttack_MoveAim;
            @LeftSpecial_MoveAim.started -= instance.OnLeftSpecial_MoveAim;
            @LeftSpecial_MoveAim.performed -= instance.OnLeftSpecial_MoveAim;
            @LeftSpecial_MoveAim.canceled -= instance.OnLeftSpecial_MoveAim;
            @LeftHoldStart_MoveAim.started -= instance.OnLeftHoldStart_MoveAim;
            @LeftHoldStart_MoveAim.performed -= instance.OnLeftHoldStart_MoveAim;
            @LeftHoldStart_MoveAim.canceled -= instance.OnLeftHoldStart_MoveAim;
            @LeftHoldFinish_MoveAim.started -= instance.OnLeftHoldFinish_MoveAim;
            @LeftHoldFinish_MoveAim.performed -= instance.OnLeftHoldFinish_MoveAim;
            @LeftHoldFinish_MoveAim.canceled -= instance.OnLeftHoldFinish_MoveAim;
            @RightAttack_MoveAim.started -= instance.OnRightAttack_MoveAim;
            @RightAttack_MoveAim.performed -= instance.OnRightAttack_MoveAim;
            @RightAttack_MoveAim.canceled -= instance.OnRightAttack_MoveAim;
            @RightSpecial_MoveAim.started -= instance.OnRightSpecial_MoveAim;
            @RightSpecial_MoveAim.performed -= instance.OnRightSpecial_MoveAim;
            @RightSpecial_MoveAim.canceled -= instance.OnRightSpecial_MoveAim;
            @RightHoldStart_MoveAim.started -= instance.OnRightHoldStart_MoveAim;
            @RightHoldStart_MoveAim.performed -= instance.OnRightHoldStart_MoveAim;
            @RightHoldStart_MoveAim.canceled -= instance.OnRightHoldStart_MoveAim;
            @RightHoldFinish_MoveAim.started -= instance.OnRightHoldFinish_MoveAim;
            @RightHoldFinish_MoveAim.performed -= instance.OnRightHoldFinish_MoveAim;
            @RightHoldFinish_MoveAim.canceled -= instance.OnRightHoldFinish_MoveAim;
            @_______.started -= instance.On_______;
            @_______.performed -= instance.On_______;
            @_______.canceled -= instance.On_______;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @FreezeMovement.started -= instance.OnFreezeMovement;
            @FreezeMovement.performed -= instance.OnFreezeMovement;
            @FreezeMovement.canceled -= instance.OnFreezeMovement;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);

    // InUI
    private readonly InputActionMap m_InUI;
    private List<IInUIActions> m_InUIActionsCallbackInterfaces = new List<IInUIActions>();
    private readonly InputAction m_InUI_Up;
    private readonly InputAction m_InUI_Down;
    private readonly InputAction m_InUI_Left;
    private readonly InputAction m_InUI_Right;
    private readonly InputAction m_InUI_Select;
    public struct InUIActions
    {
        private @PlayerInputs m_Wrapper;
        public InUIActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_InUI_Up;
        public InputAction @Down => m_Wrapper.m_InUI_Down;
        public InputAction @Left => m_Wrapper.m_InUI_Left;
        public InputAction @Right => m_Wrapper.m_InUI_Right;
        public InputAction @Select => m_Wrapper.m_InUI_Select;
        public InputActionMap Get() { return m_Wrapper.m_InUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InUIActions set) { return set.Get(); }
        public void AddCallbacks(IInUIActions instance)
        {
            if (instance == null || m_Wrapper.m_InUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InUIActionsCallbackInterfaces.Add(instance);
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IInUIActions instance)
        {
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IInUIActions instance)
        {
            if (m_Wrapper.m_InUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInUIActions instance)
        {
            foreach (var item in m_Wrapper.m_InUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InUIActions @InUI => new InUIActions(this);
    public interface IInGameActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void On__________(InputAction.CallbackContext context);
        void OnDash_CursorAim(InputAction.CallbackContext context);
        void OnLeftAttack_CursorAim(InputAction.CallbackContext context);
        void OnLeftSpecial_CursorAim(InputAction.CallbackContext context);
        void OnLeftHoldStart_CursorAim(InputAction.CallbackContext context);
        void OnLeftHoldFinish_CursorAim(InputAction.CallbackContext context);
        void OnRightAttack_CursorAim(InputAction.CallbackContext context);
        void OnRightSpecial_CursorAim(InputAction.CallbackContext context);
        void OnRightHoldStart_CursorAim(InputAction.CallbackContext context);
        void OnRightHoldFinish_CursorAim(InputAction.CallbackContext context);
        void On________(InputAction.CallbackContext context);
        void OnDash_MoveAim(InputAction.CallbackContext context);
        void OnLeftAttack_MoveAim(InputAction.CallbackContext context);
        void OnLeftSpecial_MoveAim(InputAction.CallbackContext context);
        void OnLeftHoldStart_MoveAim(InputAction.CallbackContext context);
        void OnLeftHoldFinish_MoveAim(InputAction.CallbackContext context);
        void OnRightAttack_MoveAim(InputAction.CallbackContext context);
        void OnRightSpecial_MoveAim(InputAction.CallbackContext context);
        void OnRightHoldStart_MoveAim(InputAction.CallbackContext context);
        void OnRightHoldFinish_MoveAim(InputAction.CallbackContext context);
        void On_______(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnFreezeMovement(InputAction.CallbackContext context);
    }
    public interface IInUIActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
}
