//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""2d625acc-f075-4881-a46e-0a9d8435740a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""ebb0a0c2-5486-4241-a842-1e741b6711a5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""835c6ec1-a8ce-418c-a0bf-23a62364f764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftAttack_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""ede36fc0-ffc6-4227-ab97-549443fe4d4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSpecial_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""b68945a9-54ff-4f89-98ad-2928283c45ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHoldStart_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""591e7e0e-e736-4805-862b-2199caf74661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHoldFinish_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""9cff82ec-67d3-43be-af1a-fa251bc0cae2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightAttack_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""05a5f118-4cb5-4707-95bc-0fcf9b80f7b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSpecial_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""b458bd03-e856-4f5b-89e6-8da48167df1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHoldStart_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""d7fedef8-db6b-46db-875a-07d5aae0933f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHoldFinish_CursorAim"",
                    ""type"": ""Button"",
                    ""id"": ""6944e948-ee74-42f7-8db1-34f312913d0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash_MoveAim"",
                    ""type"": ""Button"",
                    ""id"": ""be7e15c2-d544-4cc8-9874-03d6dbca7466"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""ad44f849-6f7e-4544-85ce-47d92a95273d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""a374a599-2756-4be9-aa60-639f72424b82"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""52ba9251-555d-4d1b-bd82-2ef218d9b70e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9c5f7af7-edad-4e07-bb4b-e1a515e5d701"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""35c1c48e-28e8-43b4-869f-2c010cbb7c7b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cb07142a-dc44-41b1-83de-672dba18126b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5544f6aa-c0e0-4d95-92d5-8c62c3c5d8a0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8f29bb2-ce9f-4b5c-bb87-187cae6a1a57"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df598ed1-f0c6-4758-9c3e-543ea5b045a9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash_MoveAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e71ad0a-8f3a-4d9d-a9ac-67c8b256871e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAttack_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be8b19a2-d0ea-4c65-9476-bb6df62201c3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightAttack_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""351f8a5d-5090-4787-842a-7bd5d547b536"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldStart_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feea3e16-5d3a-437d-96f6-531edc11ce47"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHoldFinish_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1b8dd98-143b-4f62-9edb-11931700755e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldStart_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d5426ea-fc17-4caf-90fe-241357cf6006"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHoldFinish_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd50dffe-d4e3-4994-be40-50c3bdf5037c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSpecial_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1996d5ae-8aa1-49ae-b3a4-e8b0df9d925c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSpecial_CursorAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Movement = m_InGame.FindAction("Movement", throwIfNotFound: true);
        m_InGame_Dash_CursorAim = m_InGame.FindAction("Dash_CursorAim", throwIfNotFound: true);
        m_InGame_LeftAttack_CursorAim = m_InGame.FindAction("LeftAttack_CursorAim", throwIfNotFound: true);
        m_InGame_LeftSpecial_CursorAim = m_InGame.FindAction("LeftSpecial_CursorAim", throwIfNotFound: true);
        m_InGame_LeftHoldStart_CursorAim = m_InGame.FindAction("LeftHoldStart_CursorAim", throwIfNotFound: true);
        m_InGame_LeftHoldFinish_CursorAim = m_InGame.FindAction("LeftHoldFinish_CursorAim", throwIfNotFound: true);
        m_InGame_RightAttack_CursorAim = m_InGame.FindAction("RightAttack_CursorAim", throwIfNotFound: true);
        m_InGame_RightSpecial_CursorAim = m_InGame.FindAction("RightSpecial_CursorAim", throwIfNotFound: true);
        m_InGame_RightHoldStart_CursorAim = m_InGame.FindAction("RightHoldStart_CursorAim", throwIfNotFound: true);
        m_InGame_RightHoldFinish_CursorAim = m_InGame.FindAction("RightHoldFinish_CursorAim", throwIfNotFound: true);
        m_InGame_Dash_MoveAim = m_InGame.FindAction("Dash_MoveAim", throwIfNotFound: true);
        m_InGame_MousePosition = m_InGame.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Movement;
    private readonly InputAction m_InGame_Dash_CursorAim;
    private readonly InputAction m_InGame_LeftAttack_CursorAim;
    private readonly InputAction m_InGame_LeftSpecial_CursorAim;
    private readonly InputAction m_InGame_LeftHoldStart_CursorAim;
    private readonly InputAction m_InGame_LeftHoldFinish_CursorAim;
    private readonly InputAction m_InGame_RightAttack_CursorAim;
    private readonly InputAction m_InGame_RightSpecial_CursorAim;
    private readonly InputAction m_InGame_RightHoldStart_CursorAim;
    private readonly InputAction m_InGame_RightHoldFinish_CursorAim;
    private readonly InputAction m_InGame_Dash_MoveAim;
    private readonly InputAction m_InGame_MousePosition;
    public struct InGameActions
    {
        private @PlayerInputs m_Wrapper;
        public InGameActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_InGame_Movement;
        public InputAction @Dash_CursorAim => m_Wrapper.m_InGame_Dash_CursorAim;
        public InputAction @LeftAttack_CursorAim => m_Wrapper.m_InGame_LeftAttack_CursorAim;
        public InputAction @LeftSpecial_CursorAim => m_Wrapper.m_InGame_LeftSpecial_CursorAim;
        public InputAction @LeftHoldStart_CursorAim => m_Wrapper.m_InGame_LeftHoldStart_CursorAim;
        public InputAction @LeftHoldFinish_CursorAim => m_Wrapper.m_InGame_LeftHoldFinish_CursorAim;
        public InputAction @RightAttack_CursorAim => m_Wrapper.m_InGame_RightAttack_CursorAim;
        public InputAction @RightSpecial_CursorAim => m_Wrapper.m_InGame_RightSpecial_CursorAim;
        public InputAction @RightHoldStart_CursorAim => m_Wrapper.m_InGame_RightHoldStart_CursorAim;
        public InputAction @RightHoldFinish_CursorAim => m_Wrapper.m_InGame_RightHoldFinish_CursorAim;
        public InputAction @Dash_MoveAim => m_Wrapper.m_InGame_Dash_MoveAim;
        public InputAction @MousePosition => m_Wrapper.m_InGame_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Dash_CursorAim.started += instance.OnDash_CursorAim;
            @Dash_CursorAim.performed += instance.OnDash_CursorAim;
            @Dash_CursorAim.canceled += instance.OnDash_CursorAim;
            @LeftAttack_CursorAim.started += instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.performed += instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.canceled += instance.OnLeftAttack_CursorAim;
            @LeftSpecial_CursorAim.started += instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.performed += instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.canceled += instance.OnLeftSpecial_CursorAim;
            @LeftHoldStart_CursorAim.started += instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.performed += instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.canceled += instance.OnLeftHoldStart_CursorAim;
            @LeftHoldFinish_CursorAim.started += instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.performed += instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.canceled += instance.OnLeftHoldFinish_CursorAim;
            @RightAttack_CursorAim.started += instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.performed += instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.canceled += instance.OnRightAttack_CursorAim;
            @RightSpecial_CursorAim.started += instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.performed += instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.canceled += instance.OnRightSpecial_CursorAim;
            @RightHoldStart_CursorAim.started += instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.performed += instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.canceled += instance.OnRightHoldStart_CursorAim;
            @RightHoldFinish_CursorAim.started += instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.performed += instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.canceled += instance.OnRightHoldFinish_CursorAim;
            @Dash_MoveAim.started += instance.OnDash_MoveAim;
            @Dash_MoveAim.performed += instance.OnDash_MoveAim;
            @Dash_MoveAim.canceled += instance.OnDash_MoveAim;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Dash_CursorAim.started -= instance.OnDash_CursorAim;
            @Dash_CursorAim.performed -= instance.OnDash_CursorAim;
            @Dash_CursorAim.canceled -= instance.OnDash_CursorAim;
            @LeftAttack_CursorAim.started -= instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.performed -= instance.OnLeftAttack_CursorAim;
            @LeftAttack_CursorAim.canceled -= instance.OnLeftAttack_CursorAim;
            @LeftSpecial_CursorAim.started -= instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.performed -= instance.OnLeftSpecial_CursorAim;
            @LeftSpecial_CursorAim.canceled -= instance.OnLeftSpecial_CursorAim;
            @LeftHoldStart_CursorAim.started -= instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.performed -= instance.OnLeftHoldStart_CursorAim;
            @LeftHoldStart_CursorAim.canceled -= instance.OnLeftHoldStart_CursorAim;
            @LeftHoldFinish_CursorAim.started -= instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.performed -= instance.OnLeftHoldFinish_CursorAim;
            @LeftHoldFinish_CursorAim.canceled -= instance.OnLeftHoldFinish_CursorAim;
            @RightAttack_CursorAim.started -= instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.performed -= instance.OnRightAttack_CursorAim;
            @RightAttack_CursorAim.canceled -= instance.OnRightAttack_CursorAim;
            @RightSpecial_CursorAim.started -= instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.performed -= instance.OnRightSpecial_CursorAim;
            @RightSpecial_CursorAim.canceled -= instance.OnRightSpecial_CursorAim;
            @RightHoldStart_CursorAim.started -= instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.performed -= instance.OnRightHoldStart_CursorAim;
            @RightHoldStart_CursorAim.canceled -= instance.OnRightHoldStart_CursorAim;
            @RightHoldFinish_CursorAim.started -= instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.performed -= instance.OnRightHoldFinish_CursorAim;
            @RightHoldFinish_CursorAim.canceled -= instance.OnRightHoldFinish_CursorAim;
            @Dash_MoveAim.started -= instance.OnDash_MoveAim;
            @Dash_MoveAim.performed -= instance.OnDash_MoveAim;
            @Dash_MoveAim.canceled -= instance.OnDash_MoveAim;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);
    public interface IInGameActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnDash_CursorAim(InputAction.CallbackContext context);
        void OnLeftAttack_CursorAim(InputAction.CallbackContext context);
        void OnLeftSpecial_CursorAim(InputAction.CallbackContext context);
        void OnLeftHoldStart_CursorAim(InputAction.CallbackContext context);
        void OnLeftHoldFinish_CursorAim(InputAction.CallbackContext context);
        void OnRightAttack_CursorAim(InputAction.CallbackContext context);
        void OnRightSpecial_CursorAim(InputAction.CallbackContext context);
        void OnRightHoldStart_CursorAim(InputAction.CallbackContext context);
        void OnRightHoldFinish_CursorAim(InputAction.CallbackContext context);
        void OnDash_MoveAim(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
